---
fixtures:
  symlinks:
    ipam: "#{source_dir}"
  forge_modules:
    apt: "puppetlabs-apt"
    archive: "puppet-archive"
    concat: "puppetlabs-concat"
    dhcp: "puppet-dhcp"
    dummy_service: "puppetlabs-dummy_service"
    epel: "stahnma-epel"
    firewall: "puppetlabs-firewall"
    inifile: "puppetlabs-inifile"
    ntp: "puppetlabs-ntp"
    selinux: "puppet-selinux"
    stdlib: "puppetlabs-stdlib"
    translate: "puppetlabs/translate"
    vcsrepo: "puppetlabs-vcsrepo"
    yumrepo_core: "puppetlabs-yumrepo_core"
  repositories:
    dns:
      repo: "https://github.com/ppouliot/puppet-dns"
      branch: "master"
