version: '3'
services:
  ipam1:
    image: "${USERNAME}/${IMAGE}:${VERSION}"
    container_name: ipam1
    build:
      context: .
      dockerfile: Dockerfile

  ipam2:
    image: "${USERNAME}/${IMAGE}-ubuntu:${VERSION}"
    container_name: ipam1
    build:
      context: .
      dockerfile: Dockerfile.ubuntu

  ipam3:
    image: "${USERNAME}/${IMAGE}-debian:${VERSION}"
    container_name: ipam1
    build:
      context: .
      dockerfile: Dockerfile.debian

  ipam4:
    image: "${USERNAME}/${IMAGE}-centos:${VERSION}"
    container_name: ipam1
    build:
      context: .
      dockerfile: Dockerfile.centos
